servers=[
  {
    :hostname => "Deb",
    :ip => "192.168.128.10",
    :box => "ubuntu/trusty64",
    :ram => 512,
    :cpu => 2
  },
  {
    :hostname => "RedHat",
    :ip => "192.168.128.11",
    :box => "centos/7",
    :ram => 512,
    :cpu => 2
  }
]

Vagrant.configure("2") do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        end
    end
end
 
